format = """
[](#9A348E)\
$os\
$username\
$hostname\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$python\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
$kubernetes\
[](fg:#06969A bg:#33658A)\
[ ](fg:#33658A)\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false     # Disabled by default
style = "bg:#9A348E"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = false
style_user = "bg:#9A348E"
style_root = "fg:#f44336 bg:#9A348E"
format = '[$user]($style)'
show_always = true

[hostname]
disabled = false
style = "bg:#9A348E"
format = '[@$hostname ]($style)'

[directory]
disabled = false
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[python]
disabled = false
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
disabled = false
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = false
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[docker_context]
disabled = false
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[kubernetes]
disabled = false
style = "bg:#06969A"
format = '[$symbol ($cluster) ($namespace)]($style)'

[character]
disabled = false
vimcmd_symbol = '[V](bold green)'
