# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:
  default:
    desc: 利用可能なタスクの一覧を表示します。
    cmds:
      - task --list-all --sort none

  chezmoi:diff:
    desc: chezmoi apply で適用される変更を表示します。
    cmds:
      - chezmoi diff {{.CLI_ARGS}}

  chezmoi:apply:
    desc: chezmoi で dotfiles をホームディレクトリに適用します。
    cmds:
      - chezmoi apply {{.CLI_ARGS}}

  environment:check:
    desc: 必要なツールが利用可能か確認します。
    cmds:
      - carapace --version
      - chezmoi --version
      - curl --version
      - gh --version
      - git --version
      - mise --version
      - nu --version
      - starship --version
      - ssh -V
      - task --version
